export enum WhereOperator {
    EQUALS = "$eq",
    EQUALS_INSENSITIVE = "$eqi",
    NOT_EQUALS = "$ne",
    LESS_THEN = "$lt",
    LESS_THEN_OR_EQUALS = "$lte",
    GREATER_THEN = "$gt",
    GREATER_THEN_OR_EQUALS = "$gte",
    IN = "$in",
    NOT_IN = "$notIn",
    CONTAINS = "$contains",
    NOT_CONTAINS = "$notContains",
    CONTAINS_INSENSITIVE = "$containsi",
    NOT_CONTAINS_INSENSITIVE = "$notContainsi",
    NULL = "$null",
    NOT_NULL = "$notNull",
    BETWEEN = "$between",
    STARTS_WITH = "$startsWith",
    ENDS_WITH = "$endsWith",
    OR = "$or",
    AN = "$an",
}
